#!/usr/bin/env bash
APPNAME=myApp

export GST_PLUGIN_PATH=${APPDIR}/usr/lib/x86_64-linux-gnu/gstreamer-1.0/
export GST_PLUGIN_SCANNER=${APPDIR}/usr/lib/x86_64-linux-gnu/gstreamer-1.0/gst-plugin-scanner

LD_LIBRARY_PATH="${APPDIR}/usr/lib:${APPDIR}/usr/lib/x86_64-linux-gnu:${LD_LIBRARY_PATH}" ${APPDIR}/usr/bin/${APPNAME}
